### ISSUE TITLE
SRP / DIP violation

### ISSUE THREAD

**Issue by vitalk** [MaLLLa/LeverX_Task1#1]
https://github.com/MaLLLa/LeverX_Task1/blob/336bdf3de125f0ac16e1629d4912977b39fc68e6/merger.py#L11

Please separate data reading / writing and processing. For example, implementation provided for `Merger` is bound to `Loader` implementation.

**Comment by MaLLLa** [comment]
Thanks for issue, I moved the creation of the Loader class object to main function.
